# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QMenu' do
  use_frameworks!
  
  pod 'HandyJSON', '~> 5.0.2'
  pod 'PermissionsKit-macOS', '~> 1.0.1'
  
end

target 'QMenuTarget' do
  use_frameworks!
  
  pod 'HandyJSON', '~> 5.0.2'
  pod 'PermissionsKit-macOS', '~> 1.0.1'
  
end
